version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8001:80
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony

  symfony:
    build:
      context: .
    volumes:
      - ./:/var/www
    expose:
      - 9000
    environment:
      - DATABASE_URL=mysql://root:root@mysql/code-review

  mysql:
    image: mysql:8.0
    ports:
      - "3777:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code-review

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  db_data: {}
